### ISSUE TITLE
Broken App Install

### ISSUE THREAD

**Issue by Darkknight33** [ReinerNippes/nextcloud_on_docker#101]
https://github.com/ArtificialOwl/files_fulltextsearch_tesseract/issues/38

This app hasn't been updated to 21, and causes the playbook to fail.

**Comment by ReinerNippes** [comment]
any idea how to handle this in the playbook? 
if i would include version checking i would always have to catch up with all apps. 
that is to say if i would include a when-version-in-["x", "y", "z"] clause i would have to watch all app releases and edit these lines.

**Comment by Darkknight33** [comment]
Is there a way to allow the playbook to continue installing even if the app install fails, and just report it at the end?

Was also thinking maybe include more refined app and container selections in the install file. Personally, I used a different OO container built without license restrictions. 

So, default value would be whatever the official container is, if variable is not null then install that container.

**Comment by ReinerNippes** [comment]
hi @Darkknight33 
> Is there a way to allow the playbook to continue installing

yes. it would look like this:

```yaml
- name: configure fulltextsearch app
  shell: '{{ docker_occ_cmd }} {{ item }}'
  loop:
    - config:app:set fulltextsearch search_platform --value "OCA\FullTextSearch_Elasticsearch\Platform\ElasticSearchPlatform"
    - config:app:set fulltextsearch app_navigation --value="1"
  ignore_errors: true
```
for more details: https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#ignoring-failed-commands



> Was also thinking maybe include more refined app and container selections in the install file.

possible but tricky. 
because the installation of fulltext search is far from stable. imho. e.g.: https://github.com/nextcloud/fulltextsearch/issues/600 changing variable names like in this issue will kill any attempt to automate installation. and there happened to be some of this issues also in nextcloud and other apps. 
and i want to make as easy as possible to get a running nextcloud instance. so i want the inventory as simple as possible. those who want to enhance their installation would have to tweek the playbook. 

nevertheless if you would like to share which image and installation way you are using i may have a look at it.
