### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS on fresh install

### ISSUE THREAD

**Issue by longride** [ReinerNippes/nextcloud_on_docker#62]
Hi,

great script, took a lot of work off me, so this is great. Recently I run into the ERR_TOO_MANY_REDIRECTS error.

This happens on a fresh Ubuntu 18.04 as well as Debian 10 install, and is the message I am greeted with right after the playbook finishes. I was able to recreate this behaviour with Traefik v2 and a current git pull from 6. June 2020.

Choosing a self signed certificate doesn't make a difference. The error remains in all major browsers with current updates. Deleting cookies desn't help.

All containers are up and running, even after reboot. Since the structure with Traefik and let's encrypt is a bit complicated, any ideas where I can narrow the error down?

Thanks for any help and kind regards

**Comment by azonictechnophile** [comment]
What options did you have set in the inventory file? So I can try to duplicate this issue.

**Comment by longride** [comment]
I only inserted domain and mail address. 

I also removed the following. It causes an error while installing and if I understand correctly it makes only sense to have this service if you have more than 2GB or RAM which I don't have.

`nextcloud_on_docker/roles/prep_os/tasks/tuning.yml
`
```
- name: disable transparent hugepages - copy service file
  copy:
    src: disable-transparent-huge-pages.service
    dest: '{{ service_path[ansible_distribution] }}/disable-transparent-huge-pages.service'
    owner: root
    group: root
    mode: 0644
  when: ansible_architecture == 'x86_64'

- name: enable service disable-transparent-hugepages
  service:
    name: disable-transparent-huge-pages.service
    enabled: true
    state: started
  when: ansible_architecture == 'x86_64'
```
