### ISSUE TITLE
Is this correct "docker_compose_collabora.yml"

### ISSUE THREAD

**Issue by LinuksGuru** [ReinerNippes/nextcloud_on_docker#91]
Hi!

With default setup nextcloud can't connect to collabora online - please correct if I'm wrong here, may be I did something wrong. Necessary ports opened in ufw. Collabora docker is running.

```
docker ps -a
0ddd9a40a641   collabora/code:latest                  "/bin/sh -c 'bash st…"   24 hours ago   Up 5 hours             9980/tcp 
```

Looks like need to add treafik rules. Is this correct "docker_compose_collabora.yml"?
Thanks in advance.

```
version: '3'

networks:
  traefik:
    external: true
services:
  collabora:
    image: traefik/collabora
    networks:
       - traefik
    labels:
      - traefik.enable=true
      - traefik.port=9980
      - traefik.http.routers.collabora.rule=Host(`cloud.mycompany.com`)
      - traefik.http.routers.collabora.entrypoints=websecure
      - traefik.http.routers.collabora.tls.certresolver=myhttpchallenge
      - traefik.docker.network=traefik

```
