### ISSUE TITLE
Integrate Nextcloud with Protonmail Bridge

### ISSUE THREAD

**Issue by blumberg** [ReinerNippes/nextcloud_on_docker#97]
I would like to use Protonmail as the mail server. To do so, I need to use the Protonmail Bridge. I found [this docker](https://hub.docker.com/r/shenxn/protonmail-bridge) and was wondering how can I integrate both. I don´t have much experience with Dockers, but don´t mind messing around.

I don´t know if there are others with the same interest, and maybe it can be added in this playbook or if anyone could give me some hints from where I can start.

**Comment by ReinerNippes** [comment]
several ways: 

without ansible:
- just use `docker run ... ` as described in https://hub.docker.com/r/shenxn/protonmail-bridge
- create a docker-compose file

with ansible:
- add a file protonmailbridge.yml to the folder roles/docker_container/tasks
```
- name: "Create protonmail bridge container"
  docker_container:
    name: protonmail-bridge
    image: shenxn/protonmail-bridge:{{ docker_protonmail_image | default('latest') }}
    restart_policy: always
    networks:
      - name: backend
    networks_cli_compatible: true
    volumes:
      - 'protonmail-data-vol:/root:rw'
    labels:
      com.centurylinklabs.watchtower.enable:         "true"
```
and add 

```
- name: docker protonmail bridge
  include_tasks: protonmailbridge.yml
  when: 
    - protonmail_bridge_enabled|bool
```

to roles/docker_container/tasks/main.yml

and finally you have to define two variables 

`protonmail_bridge_enabled=true` in the `inventory` 
and 
`docker_protonmail_image: latest` in group_vars/all.yml (~ line 30) 

please not that container won't be reachable from the internet since no ports are exposed and it is only connected to the backend network. if you want to change this you would have to create another network in roles/docker_container/tasks/network.yml and connect the nextcloud container as well to it.
